class AlreadyExists(Exception):
    pass


class NotFound(Exception):
    pass
